const KEY='mayaProducts', AUTH='mayaAdminSession';
let products=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||window.MAYA_DEFAULT_PRODUCTS}catch{return window.MAYA_DEFAULT_PRODUCTS}})();
const $=id=>document.getElementById(id);function persist(){localStorage.setItem(KEY,JSON.stringify(products));render()}
function showPanel(){ $('adminLogin').hidden=true;$('adminPanel').hidden=false;render() }
if(sessionStorage.getItem(AUTH)==='yes')showPanel();
$('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('adminPassword').value==='maya2026'){sessionStorage.setItem(AUTH,'yes');showPanel()}else $('loginError').textContent='Incorrect passcode.'});
$('adminLogout').addEventListener('click',()=>{sessionStorage.removeItem(AUTH);location.reload()});
function render(){$('adminProductList').innerHTML=products.map(p=>`<article class="admin-item"><div class="cart-thumb product-art tone-${p.tone}"></div><div><h3>${p.name}</h3><p>${p.category} · ₦${Number(p.price).toLocaleString()} · ${p.size||''}</p></div><div class="admin-item-actions"><button data-edit="${p.id}">Edit</button><button class="delete" data-delete="${p.id}">Delete</button></div></article>`).join('')}
function clearForm(){$('productForm').reset();$('productId').value='';$('formTitle').textContent='Add product'}
$('productForm').addEventListener('submit',e=>{e.preventDefault();const id=$('productId').value||$('productName').value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-4);const p={id,name:$('productName').value,category:$('productCategory').value,price:Number($('productPrice').value),size:$('productSize').value,badge:$('productBadge').value||'New',desc:$('productDesc').value,tone:$('productTone').value};const i=products.findIndex(x=>x.id===id);i>=0?products[i]=p:products.unshift(p);persist();clearForm()});
$('cancelEdit').addEventListener('click',clearForm);$('resetProducts').addEventListener('click',()=>{if(confirm('Restore the original product collection?')){products=[...window.MAYA_DEFAULT_PRODUCTS];persist()}});
document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]');if(ed){const p=products.find(x=>x.id===ed.dataset.edit);$('productId').value=p.id;$('productName').value=p.name;$('productCategory').value=p.category;$('productPrice').value=p.price;$('productSize').value=p.size||'';$('productBadge').value=p.badge||'';$('productDesc').value=p.desc||'';$('productTone').value=p.tone||'plum';$('formTitle').textContent='Edit product';scrollTo({top:0,behavior:'smooth'})}const del=e.target.closest('[data-delete]');if(del&&confirm('Delete this product?')){products=products.filter(x=>x.id!==del.dataset.delete);persist()}});
