const AUTH_KEY='mayaAdminSession';
const PREVIEW_PASSCODE='maya2026';
const $=id=>document.getElementById(id);
const cloneDefaults=()=> (window.MAYA_DEFAULT_PRODUCTS||[]).map(p=>({...p,gallery:[...(p.gallery||[])],benefits:[...(p.benefits||[])]}));
let products=[]; let query=''; let categoryFilter='All'; let cloudReady=false;
const money=v=>`₦${Number(v||0).toLocaleString('en-NG')}`;
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function showToast(message){const t=$('adminToast');t.textContent=message;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2500)}
function setCloudStatus(state,text){const el=$('cloudStatus');if(!el)return;el.dataset.state=state;el.querySelector('strong').textContent=text;}
function normalise(list){return (Array.isArray(list)?list:[]).map(p=>({...p,price:Number(p.price||0),gallery:Array.isArray(p.gallery)?p.gallery:[],benefits:Array.isArray(p.benefits)?p.benefits:[]}));}
async function loadCloudProducts(showMessage=false){setCloudStatus('loading','Connecting to cloud…');try{const list=await MayaCloud.getProducts();products=normalise(list);cloudReady=true;setCloudStatus('online',`${products.length} products synced`);render();if(showMessage)showToast('Cloud catalogue refreshed');}catch(e){cloudReady=false;products=products.length?products:cloneDefaults();setCloudStatus('offline','Cloud unavailable — bundled catalogue shown');render();if(showMessage)alert(e.message||'Unable to load the cloud catalogue.');}}
function showPanel(){$('adminLogin').hidden=true;$('adminPanel').hidden=false;updatePreview();loadCloudProducts();}
if(sessionStorage.getItem(AUTH_KEY)==='yes')showPanel();
$('togglePassword').addEventListener('click',()=>{const p=$('adminPassword');const show=p.type==='password';p.type=show?'text':'password';$('togglePassword').textContent=show?'Hide':'Show';});
$('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('adminPassword').value.trim()===PREVIEW_PASSCODE){sessionStorage.setItem(AUTH_KEY,'yes');$('loginError').textContent='';showPanel();}else{$('loginError').textContent='Incorrect passcode. Please try again.';$('adminPassword').focus();}});
$('adminLogout').addEventListener('click',()=>{sessionStorage.removeItem(AUTH_KEY);location.reload();});
function filteredProducts(){return products.filter(p=>{const hay=`${p.name} ${p.category} ${p.badge||''} ${p.status||''}`.toLowerCase();return(!query||hay.includes(query))&&(categoryFilter==='All'||p.category===categoryFilter);});}
function renderStats(){$('statTotal').textContent=products.length;$('statFace').textContent=products.filter(p=>p.category==='Face Care').length;$('statBody').textContent=products.filter(p=>p.category==='Body Care').length;$('statGifts').textContent=products.filter(p=>p.category==='Gift Sets').length;$('statFeatured').textContent=products.filter(p=>p.featured).length;$('statSoldOut').textContent=products.filter(p=>p.status==='soldout').length;}
function thumb(p){return p.image?`<div class="cart-thumb product-art product-photo"><img src="${escapeHtml(p.image)}" alt=""></div>`:`<div class="cart-thumb product-art tone-${escapeHtml(p.tone||'plum')}"><div class="product-pack">MS</div></div>`;}
function render(){renderStats();const list=filteredProducts();$('productCountText').textContent=`${list.length} of ${products.length} product${products.length===1?'':'s'}`;$('adminEmptyState').hidden=list.length>0;$('adminProductList').innerHTML=list.map(p=>`<article class="admin-item">${thumb(p)}<div class="admin-item-copy"><div class="admin-item-meta"><span>${escapeHtml(p.category)}</span>${p.badge?`<span>${escapeHtml(p.badge)}</span>`:''}${p.featured?'<span>Featured</span>':''}${p.status==='soldout'?'<span class="status-soldout">Sold out</span>':'<span class="status-live">Available</span>'}</div><h3>${escapeHtml(p.name)}</h3><p>${money(p.price)}${p.size?` · ${escapeHtml(p.size)}`:''}</p>${p.desc?`<small>${escapeHtml(p.desc)}</small>`:''}</div><div class="admin-item-actions"><button data-edit="${escapeHtml(p.id)}">Edit</button><button data-duplicate="${escapeHtml(p.id)}">Duplicate</button><button class="delete" data-delete="${escapeHtml(p.id)}">Delete</button></div></article>`).join('');}
function setEditMode(p=null){const editing=!!p;$('formMode').textContent=editing?'EDITING PRODUCT':'NEW PRODUCT';$('formTitle').textContent=editing?'Update product':'Add product';$('saveProduct').textContent=editing?'Update product':'Save product';$('cancelEdit').hidden=!editing;}
function clearValidation(){$('nameError').textContent='';$('priceError').textContent='';}
function clearForm(){$('productForm').reset();$('productId').value='';$('productCategory').value='Face Care';$('productTone').value='plum';$('productStatus').value='available';['productImage','gallery1','gallery2','gallery3'].forEach(id=>$(id).value='');setEditMode();clearValidation();updatePreview();}
function updatePreview(){const image=$('productImage').value.trim();const art=$('previewArt');if(image){art.className='product-art product-photo';art.innerHTML=`<span class="product-badge" id="previewBadge">${escapeHtml($('productBadge').value.trim()||'New')}</span><img src="${escapeHtml(image)}" alt="">`;}else{art.className=`product-art tone-${$('productTone').value||'plum'}`;art.innerHTML=`<span class="product-badge" id="previewBadge">${escapeHtml($('productBadge').value.trim()||'New')}</span><div class="product-pack">MS</div>`;}$('previewCategory').textContent=$('productCategory').value||'Face Care';$('previewName').textContent=$('productName').value.trim()||'Your product';$('previewSize').textContent=$('productSize').value.trim()||'Size';$('previewPrice').textContent=money($('productPrice').value);$('descCount').textContent=$('productDesc').value.length;}
['productName','productCategory','productPrice','productSize','productBadge','productDesc','productTone','productImage'].forEach(id=>$(id).addEventListener('input',updatePreview));
async function compressImage(file){if(!file)return'';if(file.size>8*1024*1024)throw new Error('Image is larger than 8MB');const bitmap=await createImageBitmap(file);const max=1400;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.84);}
async function handleImage(fileInputId,targetId){const file=$(fileInputId).files?.[0];if(!file)return;try{showToast('Preparing image…');$(targetId).value=await compressImage(file);updatePreview();showToast('Image ready for cloud upload');}catch(err){alert(err.message||'Unable to process this image.');}finally{$(fileInputId).value='';}}
[['productImageFile','productImage'],['galleryFile1','gallery1'],['galleryFile2','gallery2'],['galleryFile3','gallery3']].forEach(([f,t])=>$(f).addEventListener('change',()=>handleImage(f,t)));
$('clearImages').addEventListener('click',()=>{['productImage','gallery1','gallery2','gallery3'].forEach(id=>$(id).value='');updatePreview();showToast('Images removed from form');});
function dataUrlInfo(dataUrl,name){const match=/^data:([^;]+);base64,(.+)$/.exec(dataUrl||'');return match?{fileName:name,mimeType:match[1],base64:match[2]}:null;}
async function uploadIfNeeded(source,name){if(!source||!source.startsWith('data:'))return source;const info=dataUrlInfo(source,name);if(!info)throw new Error('Invalid image data');const result=await MayaCloud.uploadImage(info.fileName,info.mimeType,info.base64);return result.imageUrl;}
$('productForm').addEventListener('submit',async e=>{e.preventDefault();clearValidation();const name=$('productName').value.trim();const price=Number($('productPrice').value);let valid=true;if(name.length<2){$('nameError').textContent='Enter a clear product name.';valid=false;}if(!Number.isFinite(price)||price<1){$('priceError').textContent='Enter a valid price greater than zero.';valid=false;}if(!valid)return;if(!cloudReady&&!confirm('The cloud is currently unavailable. Try saving anyway?'))return;const button=$('saveProduct');const old=button.textContent;button.disabled=true;button.textContent='Saving to cloud…';try{const existingId=$('productId').value;const id=existingId||name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const image=await uploadIfNeeded($('productImage').value.trim(),`${id}-main.jpg`);const gallery=[];for(let i=1;i<=3;i++){const src=$(`gallery${i}`).value.trim();if(src)gallery.push(await uploadIfNeeded(src,`${id}-${i+1}.jpg`));}const product={id,name,category:$('productCategory').value,price,size:$('productSize').value.trim(),badge:$('productBadge').value.trim()||'New',desc:$('productDesc').value.trim(),tone:$('productTone').value,status:$('productStatus').value,featured:$('productFeatured').checked,image,gallery,benefits:$('productBenefits').value.split('\n').map(v=>v.trim()).filter(Boolean).slice(0,8),use:$('productUse').value.trim()};const response=await MayaCloud.saveProduct(product);products=normalise(response.products||await MayaCloud.getProducts());cloudReady=true;setCloudStatus('online',`${products.length} products synced`);render();clearForm();showToast(existingId?'Product updated everywhere':'Product added everywhere');}catch(error){console.error(error);alert(error.message||'The product could not be saved to the cloud.');}finally{button.disabled=false;button.textContent=old;}});
$('clearForm').addEventListener('click',clearForm);$('cancelEdit').addEventListener('click',clearForm);$('adminSearch').addEventListener('input',e=>{query=e.target.value.toLowerCase().trim();render();});$('adminCategoryFilter').addEventListener('change',e=>{categoryFilter=e.target.value;render();});
$('refreshCloud').addEventListener('click',()=>loadCloudProducts(true));
$('resetProducts').addEventListener('click',async()=>{if(!confirm('Replace the entire cloud catalogue with the bundled default collection?'))return;try{const result=await MayaCloud.importProducts(cloneDefaults());products=normalise(result.products||cloneDefaults());render();showToast('Cloud catalogue replaced with defaults');}catch(e){alert(e.message);}});
$('exportProducts').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(products,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`maya-secret-products-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);showToast('Cloud backup exported');});
$('importProducts').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported)||imported.some(x=>!x.name||!x.category||!Number.isFinite(Number(x.price))))throw new Error('Invalid product backup.');if(confirm(`Replace the cloud catalogue with ${imported.length} products?`)){showToast('Uploading catalogue…');const result=await MayaCloud.importProducts(normalise(imported));products=normalise(result.products||imported);cloudReady=true;setCloudStatus('online',`${products.length} products synced`);render();clearForm();showToast('Backup imported to every device');}}catch(error){alert(error.message||'That file is not a valid Maya’s Secret backup.');}finally{e.target.value='';}});
document.addEventListener('click',async e=>{const eb=e.target.closest('[data-edit]');if(eb){const p=products.find(x=>x.id===eb.dataset.edit);if(!p)return;$('productId').value=p.id;$('productName').value=p.name;$('productCategory').value=p.category;$('productPrice').value=p.price;$('productSize').value=p.size||'';$('productBadge').value=p.badge||'';$('productDesc').value=p.desc||'';$('productTone').value=p.tone||'plum';$('productStatus').value=p.status||'available';$('productFeatured').checked=!!p.featured;$('productImage').value=p.image||'';$('gallery1').value=p.gallery?.[0]||'';$('gallery2').value=p.gallery?.[1]||'';$('gallery3').value=p.gallery?.[2]||'';$('productBenefits').value=(p.benefits||[]).join('\n');$('productUse').value=p.use||'';setEditMode(p);clearValidation();updatePreview();document.querySelector('.admin-editor').scrollIntoView({behavior:'smooth',block:'start'});return;}const db=e.target.closest('[data-duplicate]');if(db){const s=products.find(x=>x.id===db.dataset.duplicate);if(s){const copy={...s,id:`${s.id}-copy-${Date.now().toString().slice(-5)}`,name:`${s.name} Copy`,badge:'New',featured:false,gallery:[...(s.gallery||[])],benefits:[...(s.benefits||[])]};try{const result=await MayaCloud.saveProduct(copy);products=normalise(result.products||await MayaCloud.getProducts());render();showToast('Product duplicated everywhere');}catch(err){alert(err.message);}}return;}const del=e.target.closest('[data-delete]');if(del){const p=products.find(x=>x.id===del.dataset.delete);if(p&&confirm(`Delete “${p.name}” from every device?`)){try{const result=await MayaCloud.deleteProduct(p.id);products=normalise(result.products||[]);render();showToast('Product deleted everywhere');if($('productId').value===p.id)clearForm();}catch(err){alert(err.message);}}}});
render();updatePreview();
