const KEY='mayaProducts';
const getProducts=()=>{try{return JSON.parse(localStorage.getItem(KEY))||window.MAYA_DEFAULT_PRODUCTS}catch{return window.MAYA_DEFAULT_PRODUCTS}};
let products=getProducts();let cart=JSON.parse(localStorage.getItem('mayaCart')||'[]');
const money=n=>'₦'+Number(n).toLocaleString('en-NG');
const card=p=>`<article class="product-card"><div class="product-art tone-${p.tone}"><span class="product-badge">${p.badge||p.category}</span><div class="product-pack">MS</div></div><div class="product-info"><p>${p.category}</p><h3>${p.name}</h3><small>${p.size||''}</small><strong>${money(p.price)}</strong></div><button class="add-btn" data-add="${p.id}">Add to bag</button></article>`;
function renderFeatured(){document.querySelectorAll('[data-products="featured"]').forEach(el=>el.innerHTML=products.slice(0,4).map(card).join(''))}
function renderShop(list=products){const grid=document.querySelector('#shopGrid');if(!grid)return;grid.innerHTML=list.map(card).join('');document.querySelector('.no-results').hidden=!!list.length}
function saveCart(){localStorage.setItem('mayaCart',JSON.stringify(cart));drawCart()}
function add(id){const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});saveCart();toast('Added to your bag')}
function change(id,d){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<1)cart=cart.filter(x=>x.id!==id);saveCart()}
function drawCart(){document.querySelectorAll('.bag-count').forEach(x=>x.textContent=cart.reduce((s,i)=>s+i.qty,0));const lines=document.querySelector('.cart-lines'),empty=document.querySelector('.cart-empty'),foot=document.querySelector('.cart-foot');if(!lines)return;if(!cart.length){lines.innerHTML='';empty.style.display='block';foot.style.display='none';return}empty.style.display='none';foot.style.display='block';lines.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return'';return `<div class="cart-line"><div class="cart-thumb product-art tone-${p.tone}"><div class="product-pack">MS</div></div><div><p>${p.category}</p><h3>${p.name}</h3><strong>${money(p.price*i.qty)}</strong><div class="qty"><button data-minus="${p.id}">−</button><span>${i.qty}</span><button data-plus="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`}).join('');document.querySelector('.cart-total').textContent=money(cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0))}
const openCart=()=>{document.querySelector('.cart').classList.add('open');document.querySelector('.overlay').classList.add('open')};const closeCart=()=>{document.querySelector('.cart').classList.remove('open');document.querySelector('.overlay').classList.remove('open')};
function toast(t){const x=document.querySelector('.toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){add(a.dataset.add);openCart()}const p=e.target.closest('[data-plus]');if(p)change(p.dataset.plus,1);const m=e.target.closest('[data-minus]');if(m)change(m.dataset.minus,-1);const r=e.target.closest('[data-remove]');if(r){cart=cart.filter(x=>x.id!==r.dataset.remove);saveCart()}});
document.querySelector('.bag-toggle')?.addEventListener('click',openCart);document.querySelector('.cart-close')?.addEventListener('click',closeCart);document.querySelector('.overlay')?.addEventListener('click',closeCart);document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.header nav').classList.toggle('open'));
document.querySelector('.checkout')?.addEventListener('click',()=>{if(!cart.length)return;const lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `• ${p.name} × ${i.qty} — ${money(p.price*i.qty)}`}).join('\n');const total=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+p.price*i.qty},0);window.open(`https://wa.me/2348109044321?text=${encodeURIComponent(`Hello Maya's Secret, I would like to order:\n\n${lines}\n\nEstimated total: ${money(total)}\n\nPlease confirm availability and delivery.`)}`,'_blank')});
let filter='All';const apply=()=>{let list=products.filter(p=>filter==='All'||p.category===filter);const q=document.querySelector('#shopSearch')?.value.toLowerCase().trim();if(q)list=list.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q));const s=document.querySelector('#shopSort')?.value;if(s==='low')list.sort((a,b)=>a.price-b.price);if(s==='high')list.sort((a,b)=>b.price-a.price);if(s==='name')list.sort((a,b)=>a.name.localeCompare(b.name));renderShop(list)};
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;apply()}));document.querySelector('#shopSearch')?.addEventListener('input',apply);document.querySelector('#shopSort')?.addEventListener('change',apply);
document.querySelector('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();const text=`Hello Maya's Secret,\n\nName: ${contactName.value}\nContact: ${contactReach.value}\nInterest: ${contactTopic.value}\nMessage: ${contactMessage.value}`;window.open(`https://wa.me/2348109044321?text=${encodeURIComponent(text)}`,'_blank')});
renderFeatured();renderShop();drawCart();
