(()=>{
const services={
"Massage":[["Swedish Massage",20000],["Aromatherapy Massage",20000],["Cupping Massage",35000],["Deep Tissue Massage",35000],["Hot Stone Massage",35000]],
"Facials":[["BB Glow Facial",35000],["Dermaplaning Facial",15000],["Ayurvedic Facial",30000],["Hydra Facial",20000],["PRP Facial",50000]],
"Waxing":[["Brazilian Wax",20000],["Bikini Wax",15000],["Underarm Wax",10000],["Leg Wax",18000],["Chin Wax",10000],["Full Body Wax",50000]],
"Body Treatments":[["Glow Body Polish",35000],["Brightening / Lightening Treatment",40000],["Hammam Bath",50000]],
"Wellness & Other":[["Foot Detox",20000],["Pedicure",10000],["Tag Removal",10000],["Stretch Marks Treatment",35000],["Sauna Bath",15000],["O-Shot",50000]]};
const $=s=>document.querySelector(s);const category=$('#spaCategory'),service=$('#spaService'),summary=$('#bookingSummary'),price=$('#bookingPrice'),form=$('#spaBookingForm'),date=$('#spaDate');
const money=n=>'₦'+Number(n).toLocaleString('en-NG');
function fill(cat,selected=''){service.innerHTML='<option value="">Select a service</option>';(services[cat]||[]).forEach(([name,p])=>{const o=document.createElement('option');o.value=name;o.textContent=`${name} — ${money(p)}`;o.dataset.price=p;if(name===selected)o.selected=true;service.appendChild(o)});updateSummary()}
function updateSummary(){const opt=service.options[service.selectedIndex];if(!service.value){summary.textContent='Choose a service above';price.textContent='Price will appear here';return}summary.textContent=service.value;price.textContent=opt?.dataset.price?money(opt.dataset.price):''}
category?.addEventListener('change',()=>fill(category.value));service?.addEventListener('change',updateSummary);
document.querySelectorAll('.spa-service').forEach(btn=>btn.addEventListener('click',()=>{category.value=btn.dataset.category;fill(btn.dataset.category,btn.dataset.service);summary.textContent=btn.dataset.service;price.textContent=money(btn.dataset.price);document.querySelectorAll('.spa-service.selected').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');document.querySelector('#booking').scrollIntoView({behavior:'smooth',block:'start'})}));
if(date){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());date.min=d.toISOString().split('T')[0]}
form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const opt=service.options[service.selectedIndex];const amount=opt?.dataset.price?money(opt.dataset.price):'To be confirmed';const raw=$('#spaDate').value;const formatted=raw?new Date(raw+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}):'';const msg=["Hello Maya's Secret Spa,","","I would like to request an appointment.","",`Name: ${$('#spaName').value.trim()}`,`Phone: ${$('#spaPhone').value.trim()}`,`Category: ${category.value}`,`Service: ${service.value}`,`Listed Price: ${amount}`,`Preferred Date: ${formatted}`,`Preferred Time: ${$('#spaTime').value}`,`Additional Notes: ${$('#spaNotes').value.trim()||'None'}`,"","Please confirm availability. Thank you."].join('\n');window.open('https://wa.me/2348109044321?text='+encodeURIComponent(msg),'_blank','noopener')});
})();